export { userRepository } from "./userRepository";
export { siteConfigAdminRepository } from "./siteConfigAdminRepository";
export { statsAdminRepository } from "./statsAdminRepository";
export { noticeAdminRepository } from "./noticeAdminRepository";
export { faqAdminRepository } from "./faqAdminRepository";
export { activityAdminRepository } from "./activityAdminRepository";
export { testimonialAdminRepository } from "./testimonialAdminRepository";
export { recruitmentAdminRepository } from "./recruitmentAdminRepository";
export { awardAdminRepository } from "./awardAdminRepository";
